[features]
seeds = false
skip-lint = false
[programs.localnet]
twine = "BKzDVQpoGW77U3ayBN6ELDbvEvSi2TYpSzHm8KhNmrCx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"